namespace Jlw.ModularContent
{
    /// <summary>
    /// Interface to define an individual email generated by the wizard factory.
    /// </summary>
    public interface IModularWizardContentEmail
    {
        /// <summary>Group key that is used to group all of the fields together in the database</summary>
        string GroupKey { get; set; }

        /// <summary>Email Subject</summary>
        string Subject { get; set; }

        /// <summary>Email Body</summary>
        string Body { get; set; }

        /// <summary>Additional data that may be used by the wizard factory</summary>
        object FormData { get; set; }
    }
}